### PR TITLE
Add support for `mixed`

### LINKED ISSUE #45: Support `mixed`
```
Module build failed: Error: File.js: babel-plugin-flow-react-proptypes: Encountered an unknown node in the type definition. Node: {"type":"MixedTypeAnnotation","start":160,"end":165,"loc":{"start":{"line":8,"column":13},"end":{"line":8,"column":18}}}
```

`mixed` should be able to be used in place of `any`

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #45

### CODE REVIEW

**Comment by brigand** [comment]
Thanks! Could you add a test for this? See [HACKING.md](https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/HACKING.md).

**Comment by aaronjensen** [comment]
@brigand done, I added it to the basic test because it seemed basic. lmk if you want it to have its own test. 

I also fixed a typo which I'd be happy to unfix or put in a separate commit if you like.

**Comment by aaronjensen** [comment]
btw, you may know this, if you rename `HACKING.md` to `CONTRIBUTING.md` it'll show up when someone goes to open an issue or a pull.

**Comment by brigand** [comment]
Great, and thanks for the typo fix. Published as 0.12.1.

**Comment by aaronjensen** [comment]
Awesome, thanks for the quick publish, now I can remove my `any`s 😄

**Comment by aaronjensen** [comment]
Actually @brigand it looks like the published version is still missing the mixed 😕

**Comment by brigand** [comment]
Oops, forgot to actually run the build. 0.12.2.

**Comment by aaronjensen** [comment]
Thanks!

**Pull request merged**
