### PR TITLE
Fix intersections for literals and imports

### LINKED ISSUE #71: propTypes are not created if you assign props from a pre-defined type or if you import types from another file
For example the following won't work:

```
const Link = ({ href, children }: Props) =>
   <a href={href}>children</a>

type Props = {
   href: string,
   children: any,
}
```

whereas this will:

```
const Link = ({ href, children }: {
   href: string,
   children: any,
}) =>
   <a href={href}>children</a>
```

In addition, if you import types, from other files, the type won't in fact be created in the other file. There will be nothing there. That problem becomes even worse if you're using types imported from packages, e.g. the `react-redux` flowtypes, eg if you're doing something like the following you're screwed:

```
import React from 'react'
import { connect } from 'react-redux'
import type { Store } from 'redux'
import type { Connector } from 'react-redux'

import type { Href } from './hrefToUrl' // no flow type will be converted to a propType in the other file

type OwnProps = {
  href: Href, 
  children: any, 
}

type Props = {
  dispatch: Function,
} & OwnProps // doubt an intersection will work

type Context = {
  store: Store,
}

const Link = ({ href, children }: Props) => // Props wont work cuz its not defined here
   <a href={href} onPress={(e) => e.preventDefault() || dispatch({ type: 'FOO' })}>{children}</a>

const connector: Connector<OwnProps, Props> = connect() // yea right, not happening

export default connector(Link)
```

So in short, any serious code using redux (or any 3rd party types, *or any of your own imported files*) unfortunately won't work with this otherwise great package.

### PR DESCRIPTION
**Pull request by mhaas**
Hi,

this MR fixes #71 and #75.

For intersections, the operands to the intersection are merged at transformation time. If an intersection involves imported types, then the operands are merged at run time: the transformation adds a call to Object.assign() which, when executed in the browser, will hopefully generate the correct proptypes from local and imported types.

I have yet to test runtime transformation. I wanted to put this MR out there as soon as possible to get some feedback. I could image you may want multiple, smaller MRs; I'd be happy to oblige.

Runtime transformation is slightly complicated by the fact that imported types default to prop-types.any if the require call fails (why?). I do check for this and default to {} in the context of the Object.assign call.

I added multiple tests, including simple and more advanced (recursive) scenarios.

### CODE REVIEW

**Comment by brigand** [comment]
Wow, thanks!

If I'm reading this right, the main remaining issue is that we're exporting `PropTypes.shape()` from the files (which is a function with only the 'isRequired' key), and then merging them with Object.assign which returns an object, and then passing the object as a prop type instead of a function.

If you do this:

```js
C.propTypes = {
  x: {},
};
```

You get 

```
Warning: Failed propType: C: prop type `x` is invalid; it must be a function, usually from React.PropTypes.`
```

which is why `any` is used by default.

Anytime you import a type from a file that hasn't both 1. exported the type, 2. been run through this plugin; we receive undefined when trying to import the type. This is a pretty common situation, especially when importing from node_modules. We need to fail soft here.

Thanks a lot for working on this!

**Comment by mhaas** [comment]
So you are saying that the exports are a shape, so I can't use Object.assign on them.

Is there any harm in just exporting the underlying object? For non-shapes, we can still export the function since you can only intersect two shapes (I think).

**Comment by brigand** [comment]
Yeah, exporting `{x: PropTypes.string}` instead of `PropTypes.shape({x: PropTypes.string})` seems good. Then wrap it in a PropTypes.shape in the importing file if it's not already a function, both in the intersection case and in the normal case.

**Comment by mhaas** [comment]
Do I need to wrap in a shape in the import side? I figured I could use shapes and objects interchangeably when assigning to `Foo.proptypes`, even nesting them.

**Comment by brigand** [comment]
Yeah, you need to pass functions as propTypes, and the keys you pass to shape need to be functions.

**Comment by mhaas** [comment]
Sorry, but I am seeing in the tests is that Foo.propTypes just is assigned a regular object, not a shape; with the keys being keys and the values being functions.

**Comment by brigand** [comment]
Yeah, I'm not explaining very well. 

```js
C.propTypes =
// this needs to be an object
{
  foo:
    // this needs to be a function
    PropTypes.shape({})
}
```

So `C.propTypes = {foo: {}}` is invalid and will error.

We need something like

```js
C.propTypes = {
  foo: PropTypes.shape(Object.assign({}, importedType, b)),
};
```

Where `importedType` needs to be an object, not a `PropTypes.shape(object)` for assign to work correctly.

**Comment by mhaas** [comment]
Got it, ok. That will make the AST generation code a bit more complex, because now I need to know if I am in intersection context or if I am in value/shape context. I suppose I do know that whenever I am processing the new runtime merge type, I will need to produce objects when recursing. Otherwise, for top-level invocations or non-merge types, all recursive calls will need to yield functions 

I will take a look tomorrow.

**Comment by mhaas** [comment]
@brigand I think I got it now. I also added some tests which actually render the components and check console.error, so we know if the generated code actually works.

**Comment by mhaas** [comment]
@brigand Ah, hold on - I just actually tried a nested intersection and it turns out; doesn't quite work yet :)

**Comment by mhaas** [comment]
@brigand I think I am done for now - looking forward to your feedback!

**Comment by mhaas** [comment]
@brigand Oops, found a bug. I do need to check if the imported variable is a function, not if it's an object - the latter check won't work.

I discovered this while adding support for non-shape/non-object exports; I have pushed the related code + tests here as well.

**Comment by brigand** [comment]
@mhaas seems the tests are failing in CI.

**Comment by mhaas** [comment]
@brigand Better now.

**Comment by brigand** [comment]
Tested on a scratch project, seems to be working great. Thanks for working on this!

Published as 3.0.0.

**Comment by mhaas** [comment]
@brigand Thank you for providing a great base :)

**Comment by mhaas** [comment]
@brigand Would you like a MR for a changelog?

**Comment by brigand** [comment]
That'd be great

**Pull request merged**
