### PR TITLE
use props value rather than undefined `value` variable

### PR DESCRIPTION
**Pull request by arahansen**
This template was looking for a `value` variable that is never defined.

### CODE REVIEW

**Comment by arahansen** [comment]
The second commit here, 4936cace1b1001f1579cb036c957bae398a9b591, is just a suggestion.

It slightly changes the behavior when erroring. I was finding that React will swallow the error message and not tell me what the value being passed was that prop-types was erroring on.

By logging first, we would get the error message provided by this lib, as well as React's prop-type validation error messaging.

I'm ok pulling the second commit out if this does not align with what this plugin should do.

**Comment by brigand** [comment]
Thanks! What's the purpose of logging the error? React should do that for you.

**Comment by arahansen** [comment]
React's messaging says something like "Invalid prop `foo` passed to MyComp"

Whereas this plugin's messaging is a bit more descriptive by including the prop name, component name *and* the prop value that was set. This makes debugging a bit easier.

Unless I'm mistaken, and React "should" be providing the prop value too? Either way, I'm cool not including the console message.

**Comment by brigand** [comment]
Odd, it should be showing the full error message. Try throwing it instead of returning it. If that doesn't work, I'll take both commits.

**Comment by arahansen** [comment]
throwing looks like it does the trick! 👍

**Comment by brigand** [comment]
Thanks!

**Comment by brigand** [comment]
v3.4.2

**Pull request merged**
