### PR TITLE
Fix issue 96 type annotations with member expressions

### PR DESCRIPTION
**Pull request by mhaas**

### CODE REVIEW

**Comment by brigand** [comment]
You added a test, but I don't see the snapshot. Let me know when it's ready to merge.

**Comment by mhaas** [comment]
@brigand I added the missing file - commit is amended.

**Comment by brigand** [comment]
I'd like to be extra safe and guard against each property in the chain being undefined/null.

**Comment by mhaas** [comment]
I added some checks against null/undefined in 716d0a5. Please double-check if this is correct.

In particular,` _some_class.SomeClass` is not checked - I don't think I can check if `_some_class` exists because that is generated by babel for the import. However, the entire expression `_some_class.SomeClass` is checked.

**Comment by brigand** [comment]
I think this is good. Published as 3.2.0.

**Comment by mhaas** [comment]
@brigand Great, thank you!

**Pull request merged**
